name: counter

packages:
  - "**"
  - "packages/**"

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  postbootstrap: make precommit

  analyze:
    run: flutter pub global run melos exec -- "flutter analyze"
    description: Run `flutter analyze` in all packages

  format:
    run: flutter pub global run melos exec -- "flutter format . --set-exit-if-changed"
    description: Run `flutter format .` in all packages

  test:
    run: flutter pub global run melos exec --dir-exists=test -- "flutter test"
    description: Run `flutter test` in all packages

  build_runner:
    run: flutter pub global run melos exec -- "flutter pub run build_runner build --delete-conflicting-outputs"
    description: Run `flutter build_runner` in all packages
    select-package:
      ignore:
        - "storage"
        - "config"
        - "localization"
        - "dls"
