default_platform(:ios)

platform :ios do

    desc 'Create keychain'
      lane :produce_keychain do
        create_keychain(
          name: "FlutterCatalyst_prod",
          password: ENV["KEYCHAIN_PASS"],
          unlock: true,
          timeout: 0,
          lock_when_sleeps: true
    )
    end

    desc 'Fetch certificates and provisioning profiles'
    lane :certificates do
      produce_keychain
      match(app_identifier: 'com.catalyst.flutterstarter',type: 'adhoc', readonly: true,keychain_name: 'FlutterCatalyst_prod',keychain_password: ENV["KEYCHAIN_PASS"])
    end

    desc 'Build ipa for ios device'
    lane :build do
        increment_build_number(
          build_number: ENV['BUNDLE_VERSION']
        )
        increment_version_number(
          version_number: ENV['BUNDLE_SHORT_VERSION']
        )
        gym(
            scheme: "production",
            workspace: 'Runner.xcworkspace',
            # project: './ios/YourAppName.xcodeproj', # Use this command if you don't have an iOS .xcworkspace file.
            configuration: 'Release-production',
            export_method: 'ad-hoc',
            export_options: {
              "provisioningProfiles": {
                "com.catalyst.flutterstarter": "catalystFlutterAdHoc"
              },
            }
          )
    end

    desc 'Beta distribution to Firebase'
      lane :distribute do
        firebase_app_distribution(
          app:ENV['FIREBASE_APP_ID_IOS'],
          release_notes: ENV['RELEASE_NOTES'],
          groups:"catalyst",
          firebase_cli_token:ENV['FIREBASE_CLI_TOKEN']
        )
      end

    desc 'Delete Keychain'
      lane :remove_keychain do
        delete_keychain(
          name: "FlutterCatalyst_prod",
        )
    end 

  end

