default_platform(:android)

platform :android do
  desc "Upload Android App to Firebase"
  lane :distribute do
      gradle(
        tasks: ["assemble#{ENV['SELECTED_FLAVOR']}Release","bundle#{ENV['SELECTED_FLAVOR']}Release"],
        properties: { 'versionCode' => ENV['RELEASE_BUILD_NUMBER'] , 'versionName' => ENV['RELEASE_VERSION']}
      )

      firebase_app_distribution(
          app: ENV['FIREBASE_APP_ID'],
          groups: 'catalyst',
          release_notes: ENV['RELEASE_NOTES'],
          android_artifact_type: "APK",
          android_artifact_path: "../build/app/outputs/apk/production/release/app-production-release.apk",
          firebase_cli_token:ENV['FIREBASE_CLI_TOKEN'],
      )
  end
end
