name: Static Check

on:
  workflow_dispatch:
  workflow_call:

jobs:
  static-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: trufflehog-actions-scan
        uses: edplato/trufflehog-actions-scan@master
        with:
          scanArguments: "--regex --entropy=False --max_depth=5 --exclude_paths tools/trufflehog_exclude_patterns.txt"


      - name: Flutter action
        uses: subosito/flutter-action@v2.7.0
        with:
            flutter-version: '3.7.11'
            channel: 'stable'

      - run: flutter --version

      - name: Setup melos
        run: flutter pub global activate melos 2.9.0

      - name: Install dependencies
        run: make bootstrap

      - name: Verify formatting
        run: make run/format

      - name: Analyze project source
        run: make run/analyze

      - name: Run tests
        run: make run/test


