name: Release Android

on:
  workflow_dispatch:
    inputs:
      flavor:
        description: 'Select Flavor'
        type: choice
        options:
          - production
        required: true
      version_name:
        description: 'Release Version'
        required: false
      release_notes:
        description: 'Release Notes'
        required: false

jobs:
  static-checks:
    uses: ./.github/workflows/ci.yml

  release-android:
    runs-on: ubuntu-latest
    needs: [ static-checks ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Flutter action
        uses: subosito/flutter-action@v2.7.0
        with:
          flutter-version: '3.3.1'
          channel: 'stable'

      - name: Setup melos
        run: flutter pub global activate melos 2.9.0

      - name: Install dependencies
        run: make bootstrap

      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          key: cache-${{ matrix.os }}-gradle
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/

      - name: Cache Gems
        uses: actions/cache@v3
        with:
          path: |
            vendor/bundle
          key: cache-${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}

      - name: Install Fastlane
        run: |
          cd android/
          bundle config path vendor/bundle
          bundle install
          bundle update fastlane

      - name: Setup secrets
        run: |
          echo ${{ secrets.APP_UPLOAD_SIGNING_KEYSTORE_B64 }} > upload_signing_keystore.jks.b64
          base64 -d -i upload_signing_keystore.jks.b64 > android/app/upload-key.jks

      - name: Release android beta apk to firebases
        run: |
          export SIGNING_KEY_ALIAS=${{ secrets.SIGNING_KEY_ALIAS }}
          export SIGNING_KEY_PASSWORD=${{ secrets.SIGNING_KEY_PASSWORD }}
          export SIGNING_KEYSTORE_PATH=upload-key.jks
          export SIGNING_KEYSTORE_PASSWORD=${{ secrets.SIGNING_KEYSTORE_PASSWORD}}
          export FIREBASE_CLI_TOKEN=${{ secrets.FIREBASE_CLI_TOKEN }}
          export FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}
          export RELEASE_BUILD_NUMBER=${GITHUB_RUN_NUMBER}
          export RELEASE_VERSION=${{ github.event.inputs.version_name }}
          export RELEASE_NOTES=${{ github.event.inputs.release_notes }}
          export SELECTED_FLAVOR=${{ github.event.inputs.flavor }}
          cd android/
          bundle exec fastlane distribute

      - name: Upload mappings.txt, sourcemaps and apk
        uses: actions/upload-artifact@v3
        with:
          path: |
            build/app/outputs/apk/**/**/*.apk
            build/app/outputs/mapping/**/mapping.txt


